server:
 error:
  include-message: always
  include-binding-errors: always

spring:
 datasource:
  password: "mysqldb"
  url: jdbc:mysql://localhost:3306/registration
  username: "root"
 jpa:
  hibernate:
   ddl-auto: create-drop
  properties: 
   hibernate: 
    dialect: org.hibernate.dialect.MySQL5Dialect
    format_sql: true
  show-sql: true